title: Haiqin Wang
description: Postdoc Research Scholar at Harvey Mudd College
url: "https://whq2605.github.io"
baseurl: ""

# Author info
author:
  name: Haiqin Wang
  position: Postdoctoral Researcher
  institution: Harvey Mudd College
  department: Department of Chemistry
  email: haiwang@g.hmc.edu
  google_scholar: "https://scholar.google.com/citations?user=WXsYVfsAAAAJ&hl=en"
  github: "whq2605"
  orcid: "0000-0002-4969-220X"
  twitter: ""
  avatar: /assets/img/profile.jpg

# Navigation links
nav_links:
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: Teaching
    url: /teaching/
  - title: Notes
    url: /notes/
  - title: CV
    url: /assets/pdf/CV.pdf

# Jekyll build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Include _pages in processing
include: ["_pages"]

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.gem"
  - scripts/
  - README.md
  - vendor/

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
